Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pathlib import Path
data = Path(Path('.').absolute().parent.parent,'10.0.19044.0-versioninfo-system32-winprogiles-recurse.json')
print(data)
win2022_sys32_ver_data = json.loads(data.read_bytes())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn [5], line 4[0m
[1;32m      2[0m data [38;5;241m=[39m Path(Path([38;5;124m'[39m[38;5;124m.[39m[38;5;124m'[39m)[38;5;241m.[39mabsolute()[38;5;241m.[39mparent[38;5;241m.[39mparent,[38;5;124m'[39m[38;5;124m10.0.19044.0-versioninfo-system32-winprogiles-recurse.json[39m[38;5;124m'[39m)
[1;32m      3[0m [38;5;28mprint[39m(data)
[0;32m----> 4[0m win2022_sys32_ver_data [38;5;241m=[39m json[38;5;241m.[39mloads([43mdata[49m[38;5;241;43m.[39;49m[43mread_bytes[49m[43m([49m[43m)[49m)

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/pathlib.py:1126[0m, in [0;36mPath.read_bytes[0;34m(self)[0m
[1;32m   1122[0m [38;5;28;01mdef[39;00m [38;5;21mread_bytes[39m([38;5;28mself[39m):
[1;32m   1123[0m     [38;5;124;03m"""[39;00m
[1;32m   1124[0m [38;5;124;03m    Open the file in bytes mode, read it, and close the file.[39;00m
[1;32m   1125[0m [38;5;124;03m    """[39;00m
[0;32m-> 1126[0m     [38;5;28;01mwith[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m   1127[0m         [38;5;28;01mreturn[39;00m f[38;5;241m.[39mread()

File [0;32m/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/pathlib.py:1119[0m, in [0;36mPath.open[0;34m(self, mode, buffering, encoding, errors, newline)[0m
[1;32m   1117[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m mode:
[1;32m   1118[0m     encoding [38;5;241m=[39m io[38;5;241m.[39mtext_encoding(encoding)
[0;32m-> 1119[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_accessor[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43mbuffering[49m[43m,[49m[43m [49m[43mencoding[49m[43m,[49m[43m [49m[43merrors[49m[43m,[49m
[1;32m   1120[0m [43m                           [49m[43mnewline[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/runner/work/cvedata/cvedata/10.0.19044.0-versioninfo-system32-winprogiles-recurse.json'
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/cvedata/cvedata/10.0.19044.0-versioninfo-system32-winprogiles-recurse.json'

